### ISSUE TITLE
Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by gabrielpatricksouza** [msayed-net/localize_and_translate#23]
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
#0      LocalizedApp.restart (package:localize_and_translate/localize_and_translate.dart:20:58)
#1      LocalizeAndTranslate.setNewLanguage (package:localize_and_translate/src/main.dart:134:20)
<asynchronous suspension>

**Comment by msayed-net** [comment]
I believe it's implementation related, could you share your code implementation
